"""Baseline

Revision ID: a482b45ed7e8
Revises: 
Create Date: 2026-01-15 14:17:24.058095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a482b45ed7e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('supplier_code'))

    op.drop_table('suppliers')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('serial_number'))

    op.drop_table('units')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('users')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('item_code'))

    op.drop_table('items')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('category_name'))

    op.drop_table('categories')
    with op.batch_alter_table('barang_keluar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('transaction_code'))

    op.drop_table('barang_keluar')
    with op.batch_alter_table('barang_masuk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('transaction_code'))

    op.drop_table('barang_masuk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang_masuk',
    sa.Column('barang_masuk_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_date', sa.DATE(), nullable=False),
    sa.Column('supplier_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_price', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('completed', 'pending', 'cancelled'), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('barang_masuk_ibfk_3')),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name=op.f('barang_masuk_ibfk_2')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('barang_masuk_ibfk_1')),
    sa.PrimaryKeyConstraint('barang_masuk_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('barang_masuk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('transaction_code'), ['transaction_code'], unique=True)

    op.create_table('barang_keluar',
    sa.Column('barang_keluar_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_date', sa.DATE(), nullable=False),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_price', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('destination_type', mysql.ENUM('event', 'sale', 'return', 'adjustment', 'damage'), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('completed', 'pending', 'cancelled'), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approved_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], name=op.f('barang_keluar_ibfk_3')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('barang_keluar_ibfk_2')),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name=op.f('barang_keluar_ibfk_1')),
    sa.PrimaryKeyConstraint('barang_keluar_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('barang_keluar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('transaction_code'), ['transaction_code'], unique=True)

    op.create_table('categories',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('categories_ibfk_1')),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('category_name'), ['category_name'], unique=True)

    op.create_table('items',
    sa.Column('item_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('unit_of_measure', mysql.VARCHAR(length=20), server_default=sa.text("'pcs'"), nullable=False),
    sa.Column('purchase_price', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('selling_price', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'inactive'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('stock_quantity', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('minimum_stock', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('items_ibfk_1')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('items_ibfk_2')),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('item_code'), ['item_code'], unique=True)

    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'manager', 'staff'), server_default=sa.text("'staff'"), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'inactive'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('users_ibfk_1')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('units',
    sa.Column('unit_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('barang_masuk_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serial_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('unit_status', mysql.ENUM('good', 'damaged', 'maintenance', 'retired'), server_default=sa.text("'good'"), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('assigned_to', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], name=op.f('units_ibfk_3')),
    sa.ForeignKeyConstraint(['barang_masuk_id'], ['barang_masuk.barang_masuk_id'], name=op.f('units_ibfk_1')),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name=op.f('units_ibfk_2')),
    sa.PrimaryKeyConstraint('unit_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('serial_number'), ['serial_number'], unique=True)

    op.create_table('suppliers',
    sa.Column('supplier_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('supplier_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('contact_person', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('postal_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('payment_terms', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'inactive'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('suppliers_ibfk_1')),
    sa.PrimaryKeyConstraint('supplier_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('supplier_code'), ['supplier_code'], unique=True)

    op.create_table('transaction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('transaction_ibfk_2')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('transaction_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
